import 'package:mobile/components/service_offer/service_preview_info.dart';
class FakeData {
  static List<ServicePreviewInfo> mockData = [
    ServicePreviewInfo(
      providerName: "Ali Khan",
      location: "Karachi, Pakistan",
      categoryName: "Barber",
      service: ["Haircut", "Shaving", "Hair Spa"],
      rating: 4.5,
      experience: 5.0,
      clients: 120,
      description: "Professional barber with 5 years of experience.",
      profileImage: "assets/images/user.png",
    ),
    ServicePreviewInfo(
      providerName: "Ali Khan",
      location: "Karachi, Pakistan",
      categoryName: "Barber",
      service: ["Haircut", "Shaving", "Hair Spa"],
      rating: 4.5,
      experience: 5.0,
      clients: 120,
      description: "Professional barber with 5 years of experience.",
      profileImage: "assets/images/user.png",
    ),
    ServicePreviewInfo(
      providerName: "Ali Khan",
      location: "Karachi, Pakistan",
      categoryName: "Barber",
      service: ["Haircut", "Shaving", "Hair Spa"],
      rating: 4.5,
      experience: 5.0,
      clients: 120,
      description: "Professional barber with 5 years of experience.",
      profileImage: "assets/images/user.png",
    ),
    ServicePreviewInfo(
      providerName: "Ali Khan",
      location: "Karachi, Pakistan",
      categoryName: "Barber",
      service: ["Haircut", "Shaving", "Hair Spa"],
      rating: 4.5,
      experience: 5.0,
      clients: 120,
      description: "Professional barber with 5 years of experience.",
      profileImage: "assets/images/user.png",
    ),
    ServicePreviewInfo(
      providerName: "Ali Khan",
      location: "Karachi, Pakistan",
      categoryName: "Barber",
      service: ["Haircut", "Shaving", "Hair Spa"],
      rating: 4.5,
      experience: 5.0,
      clients: 120,
      description: "Professional barber with 5 years of experience.",
      profileImage: "assets/images/user.png",
    ),
  ];
}